///set starting values
global.points = 0;
global.life = 3;
global.sector = 0;
global.shotpower = 0;
global.debug = false;
global.super = false;
global.shieldpower = 0;
global.warp = true;
warptime = 0;
global.globaldirection = 0;
global.globalspeed = 0;
//global.worldpadding = 500;
